using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using Toobit.Net.Enums;
using Toobit.Net.Objects.Internal;
using Toobit.Net.Objects.Models;
using Toobit.Net.Objects.Sockets;

namespace Toobit.Net.Converters
{
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(double))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]

    [JsonSerializable(typeof(ToobitServerTime))]
    [JsonSerializable(typeof(ToobitExchangeInfo))]
    [JsonSerializable(typeof(SymbolFilterType))]
    [JsonSerializable(typeof(ToobitTrade[]))]
    [JsonSerializable(typeof(ToobitOrderBook))]
    [JsonSerializable(typeof(ToobitKline[]))]
    [JsonSerializable(typeof(ToobitTicker[]))]
    [JsonSerializable(typeof(ToobitPrice[]))]
    [JsonSerializable(typeof(ToobitBookTicker[]))]
    [JsonSerializable(typeof(SocketRequest))]
    [JsonSerializable(typeof(PingRequest))]
    [JsonSerializable(typeof(PingResponse))]
    [JsonSerializable(typeof(SocketUpdate<ToobitTradeUpdate[]>))]
    [JsonSerializable(typeof(SocketUpdate<ToobitTickerUpdate[]>))]
    [JsonSerializable(typeof(SocketUpdate<ToobitKlineUpdate[]>))]
    [JsonSerializable(typeof(SocketUpdate<ToobitOrderBookUpdate[]>))]
    [JsonSerializable(typeof(ToobitWithdrawResult))]
    [JsonSerializable(typeof(ToobitWithdrawal[]))]
    [JsonSerializable(typeof(ToobitDepositAddress))]
    [JsonSerializable(typeof(ToobitDeposit[]))]
    [JsonSerializable(typeof(ToobitUserBalance))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(ToobitResult))]
    [JsonSerializable(typeof(ToobitTransaction[]))]
    [JsonSerializable(typeof(ToobitSubAccount[]))]
    [JsonSerializable(typeof(ToobitOrder))]
    [JsonSerializable(typeof(ToobitOrder[]))]
    [JsonSerializable(typeof(ToobitSuccess))]
    [JsonSerializable(typeof(ToobitUserTrade[]))]
    [JsonSerializable(typeof(ToobitAccountUpdate[]))]
    [JsonSerializable(typeof(ToobitOrderUpdate[]))]
    [JsonSerializable(typeof(ToobitUserTradeUpdate[]))]
    [JsonSerializable(typeof(ToobitIndexPrices))]
    [JsonSerializable(typeof(ToobitWrapper<ToobitFuturesKline[]>))]
    [JsonSerializable(typeof(ToobitWrapper<ToobitMarkKline[]>))]
    [JsonSerializable(typeof(ToobitMarkPrice))]
    [JsonSerializable(typeof(ToobitFundingRate[]))]
    [JsonSerializable(typeof(ToobitFundingHistory[]))]
    [JsonSerializable(typeof(ToobitMarginType))]
    [JsonSerializable(typeof(ToobitLeverage))]
    [JsonSerializable(typeof(ToobitLeverageInfo[]))]
    [JsonSerializable(typeof(ToobitFuturesBalance[]))]
    [JsonSerializable(typeof(ToobitPositionMargin))]
    [JsonSerializable(typeof(ToobitFuturesTransaction[]))]
    [JsonSerializable(typeof(ToobitFeeRates))]
    [JsonSerializable(typeof(ToobitFuturesOrder))]
    [JsonSerializable(typeof(ToobitFuturesOrder[]))]
    [JsonSerializable(typeof(ToobitPosition[]))]
    [JsonSerializable(typeof(ToobitTradingStop))]
    [JsonSerializable(typeof(ToobitFuturesUserTrade[]))]
    [JsonSerializable(typeof(SocketUpdate<ToobitMarkPriceUpdate[]>))]
    [JsonSerializable(typeof(SocketUpdate<ToobitMarkPriceUpdate>))]
    [JsonSerializable(typeof(SocketUpdate<ToobitIndexUpdate[]>))]
    [JsonSerializable(typeof(ToobitFuturesOrderUpdate[]))]
    [JsonSerializable(typeof(ToobitPositionUpdate[]))]
    [JsonSerializable(typeof(ToobitOrderRequest[]))]
    [JsonSerializable(typeof(ToobitDataResult<ToobitOrderResult[]>))]
    [JsonSerializable(typeof(ToobitDataResult<ToobitCancelResult[]>))]
    [JsonSerializable(typeof(ToobitListenKey))]
    internal partial class ToobitSourceGenerationContext : JsonSerializerContext
    {
    }
}
